import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";
import { NextResponse } from "next/server";

export async function POST(request: Request) {
  try {
    const { flavorId, imageId } = await request.json();
    
    if (!flavorId || !imageId) {
      return NextResponse.json({ error: "Missing parameters" }, { status: 400 });
    }

    const authHeader = request.headers.get("Authorization");
    if (!authHeader) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Call the external pipeline API
    const response = await fetch("https://api.almostcrackd.ai/pipeline/generate-captions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": authHeader
      },
      body: JSON.stringify({
        imageId,
        humorFlavorId: flavorId
      })
    });

    const data = await response.json();

    if (!response.ok) {
      throw new Error(data.message || data.error || `Pipeline error: ${response.status}`);
    }

    // Heuristic search for the caption in the response
    const captions = Array.isArray(data) ? data : (data.captions || []);
    
    if (captions.length === 0) {
      return NextResponse.json({ 
        caption: "No caption generated by pipeline",
        debug: data 
      });
    }

    const latestItem = captions[captions.length - 1];
    
    // Look for common field names
    let finalCaption = latestItem.caption_text || 
                       latestItem.caption || 
                       latestItem.content || 
                       latestItem.text;

    // If still not found, search all string properties
    if (!finalCaption) {
      for (const key in latestItem) {
        if (typeof latestItem[key] === 'string' && latestItem[key].length > 10) {
          finalCaption = latestItem[key];
          break;
        }
      }
    }

    return NextResponse.json({ 
      caption: finalCaption || "Caption data found but content empty",
      raw: data
    });

  } catch (error: any) {
    console.error("Caption generation error:", error);
    return NextResponse.json({ error: error.message || "Internal server error" }, { status: 500 });
  }
}
