import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";
import { NextResponse } from "next/server";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { flavorId, imageId } = body;
    
    if (!flavorId || !imageId) {
      return NextResponse.json({ error: "Missing flavorId or imageId" }, { status: 400 });
    }

    const authHeader = request.headers.get("Authorization");
    if (!authHeader) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Convert flavorId to number as the database uses integers
    const numericFlavorId = parseInt(flavorId);

    // Call the external pipeline API
    const response = await fetch("https://api.almostcrackd.ai/pipeline/generate-captions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": authHeader
      },
      body: JSON.stringify({
        imageId,
        humorFlavorId: numericFlavorId
      })
    });

    // Read text first to handle non-JSON responses (like server crashes)
    const responseText = await response.text();
    let data: any;
    try {
      data = JSON.parse(responseText);
    } catch (e) {
      throw new Error(`Invalid JSON from pipeline: ${responseText.substring(0, 100)}`);
    }

    if (!response.ok) {
      // The error "Cannot read properties of undefined (reading 'specificationVersion')" 
      // is likely coming from the remote server's error body.
      const errorMessage = data?.message || data?.error || responseText || `Pipeline error: ${response.status}`;
      throw new Error(errorMessage);
    }

    // Heuristic search for the caption in the response
    const captions = Array.isArray(data) ? data : (data.captions || []);
    
    if (captions.length === 0) {
      return NextResponse.json({ 
        caption: "No caption generated by pipeline",
        debug: data 
      });
    }

    const latestItem = captions[captions.length - 1];
    let finalCaption = latestItem.caption_text || 
                       latestItem.caption || 
                       latestItem.content || 
                       latestItem.text;

    if (!finalCaption) {
      for (const key in latestItem) {
        if (typeof latestItem[key] === 'string' && latestItem[key].length > 10) {
          finalCaption = latestItem[key];
          break;
        }
      }
    }

    return NextResponse.json({ 
      caption: finalCaption || "Caption data found but content empty",
      raw: data
    });

  } catch (error: any) {
    console.error("Caption generation error:", error);
    return NextResponse.json({ 
      error: error.message || "Internal server error",
      details: "Check server logs or remote API status."
    }, { status: 500 });
  }
}
